### ISSUE TITLE
Arduino package does not co-exists with SparkFun PSoC5 Arduino package

### ISSUE THREAD

**Issue by blacktigersoftware** [sparkfun/ESP8266_Thing#7]
If you have the Sparkfun Arduino PSoC5 package, installing the ESP8266_Thing package makes it disappear.  I did a full reinstall of Arduino 1.6.5, carefully following the PSoC5 steps, quiting Arduino after each step, then performed the ESP8266_Thing installation.
The reason why I make this an issue for ESP8266_Thing is that Visual Micro can still see the PSoC5 package (even though Arduino can't), but has never been able to see the ESP8266_Thing package.

**Comment by santaimpersonator** [comment]
We have since handed off the installation of ESP8266 Thing into the board manager... to the [ESP8266 core](https://github.com/esp8266/Arduino). Since, we are no longer are managing this process, I will be closing this issue. If you still have issue installing both packages, please file the issue under the appropriate repository.
